### ISSUE TITLE
Only allow .msg to be sent to .irc

### ISSUE THREAD

**Issue by ddavison** [lmtierney/slack-irc#15]
# Actual Behavior:
When a user sends `.msg user hi there`,

A private message will be sent to the `user' in IRC as well as a slack-only message (hence the . before)

# Expected Behavior:
When a user sends `.msg user hi there`,

No private message is sent.  @se-irc will reply directly to you with instructions on how to properly private message.

Nobody in slack can read the message - it would only be readable by the sender.

# Reasoning:

A private message could contain confidential information, and a user accidentally sending from #selenium could expose that information to all of slack.

**Comment by lmtierney** [comment]
Ok I *think* I get what you're asking? Instead of following through with the private message, warn the user saying to send directly to the bot? The user would then have to delete the message themselves as the bot doesn't have control over users' messages. Is that accurate?

**Comment by ddavison** [comment]
I'm thinking in the tie-in to sending "." messages (slack only messages), if there's a way the bot can detect ".msg" in the #selenium channel, and sending a direct message to the user notifying them that slack can see it.

If the bot can't delete the message, or "not" send it to the rest of slack, that'd be preferred - but if it's not possible, we can settle for se-irc pm'ing the invoking user

**Comment by lmtierney** [comment]
addressed in b2f6577, give it a whirl if you want
